### ISSUE TITLE
option to bypass changelog edit

### ISSUE THREAD

**Issue by vukbgit** [jv-k/bump-version.sh#15]
Hello, thanks for this great tool. In order to speed up the workflow I would like to bypass the "Make adjustments to [CHANGELOG.md] if required now" enter hit

Is it possible to add an option (similar to -p) so that user is not asked to hit enter anymore?

Thanks!

**Comment by jv-k** [comment]
Thanks for suggestions, it's been added to the latest version.

**Comment by vukbgit** [comment]
works like a charm, thanks
